/*
 * Unit tests for arbitrary-precision integer data type
 *
 * These tests are by no means comprehensive.  You will need to
 * add more tests of your own!  In particular, make sure that
 * you have tests for more challenging situations, such as
 *
 * - large values
 * - adding/subtracting/comparing values with different lengths
 * - special cases (carries when adding, borrows when subtracting, etc.)
 * - etc.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "apint.h"
#include "tctest.h"

typedef struct
{
	ApInt *ap0;
	ApInt *ap1;
	ApInt *ap110660361;
	ApInt *max1;
	ApInt *minus1;
	// Additional tests
	ApInt *_ap110660361;

	ApInt *hex0;
	ApInt *hexR1;
	ApInt *hexR2;
	ApInt *hexR3;
	ApInt *hexR4;
	ApInt *hex_minus1;

} TestObjs;

TestObjs *setup(void);
void cleanup(TestObjs *objs);

void testCreateFromU64(TestObjs *objs);
void testCreateFromHex(TestObjs *objs);
void testHighestBitSet(TestObjs *objs);
void testComparePosU64(TestObjs *objs);
void testCompareNegU64(TestObjs *objs);
void testFormatAsHex(TestObjs *objs);
void testAdd(TestObjs *objs);
void testSub(TestObjs *objs);
/* TODO: add more test function prototypes */
void testApInt_is_negative(TestObjs *objs);
void testAutoGenerated_add_sub();

int main(int argc, char **argv)
{
	TEST_INIT();

	if (argc > 1)
	{
		/*
		 * name of specific test case to execute was provided
		 * as a command line argument
		 */
		tctest_testname_to_execute = argv[1];
	}

	TEST(testCreateFromU64);
	TEST(testHighestBitSet);
	TEST(testComparePosU64);
	TEST(testCompareNegU64);
	TEST(testFormatAsHex);
	TEST(testAdd);
	TEST(testSub);
	// Additional tests
	TEST(testApInt_is_negative);
	TEST(testAutoGenerated_add_sub);

	TEST_FINI();
}

TestObjs *setup(void)
{
	TestObjs *objs = malloc(sizeof(TestObjs));
	objs->ap0 = apint_create_from_u64(0UL);
	objs->ap1 = apint_create_from_u64(1UL);
	objs->ap110660361 = apint_create_from_u64(110660361UL);
	objs->max1 = apint_create_from_u64(0xFFFFFFFFFFFFFFFFUL);
	objs->minus1 = apint_negate(objs->ap1);
	objs->_ap110660361 = apint_negate(objs->ap110660361);

	objs->hexR1 = apint_create_from_hex("2354afddc");	
	objs->hexR2 = apint_create_from_hex("bc43f0b6666843bc3455"); //20
	objs->hexR3 = apint_create_from_hex("9348bbbb");			 
	objs->hexR4 = apint_create_from_hex("-0000000000000000000000000000000000000000000000000000000000000000000000000000000000123");
	objs->hex0 = apint_create_from_hex("0");
	objs->hex_minus1 = apint_create_from_hex("-1");

	return objs;
}

void cleanup(TestObjs *objs)
{
	apint_destroy(objs->ap0);
	apint_destroy(objs->ap1);
	apint_destroy(objs->ap110660361);
	apint_destroy(objs->max1);
	apint_destroy(objs->minus1); // ISSUE?
	/* TODO: destroy additional members of test fixture */
	apint_destroy(objs->_ap110660361);

	apint_destroy(objs->hex0);
	apint_destroy(objs->hexR1);
	apint_destroy(objs->hexR2);
	apint_destroy(objs->hexR3);
	apint_destroy(objs->hexR4);
	apint_destroy(objs->hex_minus1);

	free(objs);
}

void testCreateFromU64(TestObjs *objs)
{
	ASSERT(0UL == apint_get_bits(objs->ap0, 0));
	ASSERT(1UL == apint_get_bits(objs->ap1, 0));
	ASSERT(110660361UL == apint_get_bits(objs->ap110660361, 0));
	ASSERT(0xFFFFFFFFFFFFFFFFUL == apint_get_bits(objs->max1, 0));
	ASSERT(0xFFFFFFFFFFFFFFFFUL == apint_get_bits(objs->max1, 0));
}

void testCreateFromHex(TestObjs *objs)
{
	ASSERT(0UL == apint_get_bits(objs->hex0, 0));
	ASSERT(0x2354afddcUL == apint_get_bits(objs->hexR1, 0));
	ASSERT(0xf0b6666843bc3421UL == apint_get_bits(objs->hexR2, 0));
	ASSERT(0xbc43UL == apint_get_bits(objs->hexR2, 1));
	ASSERT(0x9348bbbbUL == apint_get_bits(objs->hexR3, 0));
}

void testNegateApint(TestObjs *objs)
{
	// Test 0
	ASSERT(0 == apint_is_negative(objs->ap0));
	// Test pos
	ASSERT(0 == apint_is_negative(objs->ap1));
	ASSERT(0 == apint_is_negative(objs->ap110660361));
	ASSERT(0 == apint_is_negative(objs->max1));
	// Test neg
	ASSERT(1 == apint_is_negative(objs->minus1));
}

void testApInt_is_negative(TestObjs *objs)
{
	// Test 0
	ASSERT(0 == apint_is_negative(objs->ap0));
	// Test pos
	ASSERT(0 == apint_is_negative(objs->ap1));
	ASSERT(0 == apint_is_negative(objs->ap110660361));
	ASSERT(0 == apint_is_negative(objs->max1));
	// Test neg
	ASSERT(1 == apint_is_negative(objs->minus1));
}

void testHighestBitSet(TestObjs *objs)
{
	ASSERT(-1 == apint_highest_bit_set(objs->ap0));
	ASSERT(0 == apint_highest_bit_set(objs->ap1));
	ASSERT(26 == apint_highest_bit_set(objs->ap110660361));
	ASSERT(63 == apint_highest_bit_set(objs->max1));
}

void testComparePosU64(TestObjs *objs)
{
	/* 1 > 0 */
	ASSERT(apint_compare(objs->ap1, objs->ap0) > 0);
	/* 0 < 1 */
	ASSERT(apint_compare(objs->ap0, objs->ap1) < 0);
	/* 110660361 > 0 */
	ASSERT(apint_compare(objs->ap110660361, objs->ap0) > 0);
	/* 110660361 > 1 */
	ASSERT(apint_compare(objs->ap110660361, objs->ap1) > 0);
	/* 0 < 110660361 */
	ASSERT(apint_compare(objs->ap0, objs->ap110660361) < 0);
	/* 1 < 110660361 */
	ASSERT(apint_compare(objs->ap1, objs->ap110660361) < 0);
}

void testCompareNegU64(TestObjs *objs)
{
	/* 0 > -1 */
	ASSERT(apint_compare(objs->ap0, objs->minus1) > 0);
	/* -1 < 1 */
	ASSERT(apint_compare(objs->minus1, objs->ap1) < 0);
	/* 110660361 > -1 */
	ASSERT(apint_compare(objs->ap110660361, objs->minus1) > 0);
	/* -1 < 110660361 */
	ASSERT(apint_compare(objs->minus1, objs->ap110660361) < 0);

	// Additional tests big num
	/* 1 < bc43f0b6666843bc3455*/
	ASSERT(apint_compare(objs->ap1, objs->hexR2) < 0);
	/* bc43f0b6666843bc3455 > 0*/
	ASSERT(apint_compare(objs->hexR2, objs->ap0) > 0);

	/* 2354afddc < bc43f0b6666843bc3455*/
	ASSERT(apint_compare(objs->hexR1, objs->hexR2) < 0);
	/* bc43f0b6666843bc3455 = bc43f0b6666843bc3455 */
	ASSERT(apint_compare(objs->hexR2, objs->hexR2) == 0);

	ApInt *a = apint_create_from_hex("bc43b0b6666843bc3421");
	/* bc43f0b6666843bc3455 > bc43b0b6666843bc3421 */
	ASSERT(apint_compare(objs->hexR2, a) > 0);
	apint_destroy(a);
}

void testFormatAsHex(TestObjs *objs)
{
	char *s;

	ASSERT(0 == strcmp("0", (s = apint_format_as_hex(objs->ap0))));
	free(s);

	ASSERT(0 == strcmp("1", (s = apint_format_as_hex(objs->ap1))));
	free(s);

	ASSERT(0 == strcmp("6988b09", (s = apint_format_as_hex(objs->ap110660361))));
	free(s);

	ASSERT(0 == strcmp("ffffffffffffffff", (s = apint_format_as_hex(objs->max1))));
	free(s);

	// Neg
	ASSERT(0 == strcmp("-1", (s = apint_format_as_hex(objs->minus1))));
	free(s);

	ASSERT(0 == strcmp("bc43f0b6666843bc3455", (s = apint_format_as_hex(objs->hexR2))));
	free(s);

	ASSERT(0 == strcmp("-123", (s = apint_format_as_hex(objs->hexR4))));
	free(s);
}

void testAdd(TestObjs *objs)
{
	ApInt *sum, *a, *b;
	char *s;

	/* 0 + 0 = 0 */
	sum = apint_add(objs->ap0, objs->ap0);
	ASSERT(0 == strcmp("0", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* 1 + 0 = 1 */
	sum = apint_add(objs->ap1, objs->ap0);
	ASSERT(0 == strcmp("1", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* 1 + 1 = 2 */
	sum = apint_add(objs->ap1, objs->ap1);
	ASSERT(0 == strcmp("2", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* 110660361 + 1 = 110660362 */
	sum = apint_add(objs->ap110660361, objs->ap1);
	ASSERT(0 == strcmp("6988b0a", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* 1 + -1 = 0 */
	sum = apint_add(objs->ap1, objs->minus1);
	ASSERT(0 == strcmp("0", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* -1 + 1 = 0 */
	sum = apint_add(objs->minus1, objs->ap1);
	ASSERT(0 == strcmp("0", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	// large sum
	/* FFFFFFFFFFFFFFFF + 1 = 10000000000000000 */
	sum = apint_add(objs->max1, objs->ap1);
	ASSERT(0 == strcmp("10000000000000000", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	// Additional tests
	/* 1 + FFFFFFFFFFFFFFFF = 10000000000000000 */
	sum = apint_add(objs->ap1, objs->max1);
	ASSERT(0 == strcmp("10000000000000000", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	/* bc43f0b6666843bc3455 + 0 = bc43f0b6666843bc3455 */
	sum = apint_add(objs->ap0, objs->hexR2);
	ASSERT(0 == strcmp("bc43f0b6666843bc3455", (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	free(s);

	// 0s test
	a = apint_create_from_hex("-0");
	b = apint_create_from_hex("0");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("0",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	//Special case of overflow
	a = apint_create_from_hex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF");
	b = apint_create_from_hex("FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1fffffffffffffffffffffffffffffffe",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Special case of underflow for neg add
	a = apint_create_from_hex("ffffffffffffffff11111111111111111111111111111111");
	b = apint_create_from_hex("-ffffffffffffffffffffffffffffffff"); // Max Max
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("fffffffffffffffe11111111111111111111111111111112",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Additional tests
	/* neg test involving larger values */
	a = apint_create_from_hex("-7e5ff912c8ede6ccff0d56ae5a9b5459804f9");
	b = apint_create_from_hex("-6057bccd860546f03fd51bf5488d50cca96");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-7ec050cf9673ec13ef4d2bca4fe3e1aa4cf8f",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-439284b10da826ceef1ca7435a3f300a7");
	b = apint_create_from_hex("-e460e18a60c7345781147ab3ca122fd4c6b2c9dda98d2245431005e64614500cd8610d129c9bdb9cdecfa38358eb02");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-e460e18a60c7345781147ab3ca122fd4c6b2c9dda98d2245431005e64614544600ac1ded1f08ca8ea943d9274beba9",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-c8ed2c2ef8832a");
	b = apint_create_from_hex("-3bac3c2a7dd6df38b3fc4c0165d8a0ef31f523cb7614c6efe900");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-3bac3c2a7dd6df38b3fc4c0165d8a0ef31f524946340f5e86c2a",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF");
	b = apint_create_from_hex("-FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-1fffffffffffffffffffffffffffffffe",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Ruby generated tests
	// 9c9e748c5b6fb80000 + ecabb073d17420 = 9c9f61380be3897420
	a = apint_create_from_hex("9c9e748c5b6fb80000");
	b = apint_create_from_hex("ecabb073d17420");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("9c9f61380be3897420",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// 55ebd8653db5540000000000000000000000000000000 - c832d02aecd558000000 = 55ebd8653db5540000000000000000000000000000000
	a = apint_create_from_hex("55ebd8653db5540000000000000000000000000000000");
	b = apint_create_from_hex("-c832d02aecd558000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("55ebd8653db553fffffffffff37cd2fd5132aa8000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// b07f0d747da9800000000000000000000000000 - a55133a51677d800000000 = b07f0d747da9800000000000000000000000000
	a = apint_create_from_hex("b07f0d747da9800000000000000000000000000");
	b = apint_create_from_hex("-a55133a51677d800000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("b07f0d747da97ffff5aaecc5ae9882800000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// 226718cfa8ec920000000000000000000000000000000000000000000000000000000000000000000 + d04fce0ea951d80000000000000000000000000000000000000000000000000000000000000000000000000000000 = d04fce0ea951f80000000000000000000000000000000000000000000000000000000000000000000000000000000
	a = apint_create_from_hex("226718cfa8ec920000000000000000000000000000000000000000000000000000000000000000000");
	b = apint_create_from_hex("d04fce0ea951d80000000000000000000000000000000000000000000000000000000000000000000000000000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("d04fce0ea951fa6718cfa8ec920000000000000000000000000000000000000000000000000000000000000000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// 405bd2ee04d0340000000000000000000000000000000000000000000000 + ad086017f131d80000000000000000000000000000000000000000000000000000 = ad0860584d04c80000000000000000000000000000000000000000000000000000
	a = apint_create_from_hex("405bd2ee04d0340000000000000000000000000000000000000000000000");
	b = apint_create_from_hex("ad086017f131d80000000000000000000000000000000000000000000000000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("ad0860584d04c604d0340000000000000000000000000000000000000000000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// 1bd8477a5125ac00000000000000000000000000000000 - 415e606bef52340000000000 = 1bd8477a5125ac00000000000000000000000000000000
	a = apint_create_from_hex("1bd8477a5125ac00000000000000000000000000000000");
	b = apint_create_from_hex("-415e606bef52340000000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1bd8477a5125abffffffffbea19f9410adcc0000000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
	// 735d98e1a08578000000000000000000000000000000000000000000000000000000000000000000000000000000000 + 57fe7c726a7d08000000000000000000000000000000000000000000000000000000000000 = 735d98e1a08578000000000000000000000000000000000000000000000000000000000000000000000000000000000
	a = apint_create_from_hex("735d98e1a08578000000000000000000000000000000000000000000000000000000000000000000000000000000000");
	b = apint_create_from_hex("57fe7c726a7d08000000000000000000000000000000000000000000000000000000000000");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("735d98e1a08578000000057fe7c726a7d08000000000000000000000000000000000000000000000000000000000000",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
}

void testSub(TestObjs *objs)
{
	ApInt *a, *b, *diff;
	char *s;

	/* subtracting 1 from ffffffffffffffff is fffffffffffffffe */
	diff = apint_sub(objs->max1, objs->ap1);
	ASSERT(0 == strcmp("fffffffffffffffe", (s = apint_format_as_hex(diff))));
	apint_destroy(diff);
	free(s);

	/* subtracting 0 from 1 is 1 */
	diff = apint_sub(objs->ap1, objs->ap0);
	ASSERT(0 == strcmp("1", (s = apint_format_as_hex(diff))));
	ASSERT(0 == apint_compare(diff, objs->ap1));
	apint_destroy(diff);
	free(s);

	/* subtracting 1 from 1 is 0 */
	diff = apint_sub(objs->ap1, objs->ap1);
	ASSERT(0 == strcmp("0", (s = apint_format_as_hex(diff))));
	ASSERT(0 == apint_compare(diff, objs->ap0));
	apint_destroy(diff);
	free(s);

	/* subtracting 1 from 0 is -1 */
	diff = apint_sub(objs->ap0, objs->ap1);
	ASSERT(0 == (strcmp("-1", (s = apint_format_as_hex(diff)))));
	ASSERT(0 == apint_compare(diff, objs->minus1));
	apint_destroy(diff);
	free(s);

	/* test involving larger values */
	a = apint_create_from_hex("7e35207519b6b06429378631ca460905c19537644f31dc50114e9dc90bb4e4ebc43cfebe6b86d");
	b = apint_create_from_hex("9fa0fb165441ade7cb8b17c3ab3653465e09e8078e09631ec8f6fe3a5b301dc");
	diff = apint_sub(a, b);
	ASSERT(0 == strcmp("7e35207519b6afc4883c6fdd8898213a367d73b918de95f20766963b0251c622cd3ec4633b691",
					   (s = apint_format_as_hex(diff))));
	apint_destroy(diff);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	/* test involving larger values (with a negative difference) */
	a = apint_create_from_hex("9fa0fb165441ade7cb8b17c3ab3653465e09e8078e09631ec8f6fe3a5b301dc");
	b = apint_create_from_hex("7e35207519b6b06429378631ca460905c19537644f31dc50114e9dc90bb4e4ebc43cfebe6b86d");
	diff = apint_sub(a, b);
	ASSERT(0 == strcmp("-7e35207519b6afc4883c6fdd8898213a367d73b918de95f20766963b0251c622cd3ec4633b691",
					   (s = apint_format_as_hex(diff))));
	apint_destroy(diff);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
}


void testAutoGenerated_add_sub()
{

	ApInt *sum, *a, *b;
	char *s;
	// Addition

	a = apint_create_from_hex("6fedba0ce37af828527c6973e007b55fecc8645d388265dbe4ef28be080dc47ac1");
	b = apint_create_from_hex("19dd586dcd73e34aa144b2137ebfff27e3d35645f8f69dfece7e4b303bdeebfa19b");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("20dc340e9bab92cd266c78aabcc07a7de29fdc8bcc7ec45c8ccd3dbc1c5fc841c5c",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("193cc1a3ea539330683500fcbceb86d4e75adce5aa2150dc04da5c69f62f336a8ed");
	b = apint_create_from_hex("293fdf8ee06553a9b3c01a4d3bf0c982803e53f74b6a55a0b0c865a4c8f40772c39");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("427ca132cab8e6da1bf51b49f8dc5057679930dcf58ba67cb5a2c20ebf233add526",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("17c9891e2e85f0f9cf0b23f97690809ba31e6e1cde0fd9f227666486c647ba3bf99");
	b = apint_create_from_hex("1fd50dfba88c63d7cfac4adc12fb233e2118cc2e606fb58162ee2fc569208d70a18");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("379e9719d71254d19eb76ed5898ba3d9c4373a4b3e7f8f738a54944c2f6847ac9b1",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("21c112b57a6f605ff4be821ac7d501960627cf97c51f4d67ee20ecd2492a0000e5f");
	b = apint_create_from_hex("2c1ba93260dc27c4f3b805ca76f2b03c9c7796f751beae2eba923e9d46ed10abc91");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("4ddcbbe7db4b8824e87687e53ec7b1d2a29f668f16ddfb96a8b32b6f901710acaf0",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("994bc557fcc8db1640aaa13d03583b2ca8dbe3255d57799cb9a2cebf8e862a5555");
	b = apint_create_from_hex("19f301d29eff0dd668f9a9ad76ce1c21a80e61408a438432f98be9df083d0bbcb13");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2387be281ecb9b87cd0453c147039fd4729c1f72e018fbccc52616cb01256e62068",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2e6ce8070ab92f70247e76ebb70695eee88fa6154ad1b824850a5b2823ff937fd5b");
	b = apint_create_from_hex("2f7943f32ce3e54768441a1aaa820ffdfae7de9203fdd7e787302e0b577c482c0cf");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("5de62bfa379d14b78cc291066188a5ece37784a74ecf900c0c3a89337b7bdbabe2a",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("76f2e73e7c6fe8b0f408418a6a95273a2cfaa144940bdd4d7aa9650d953a92615b");
	b = apint_create_from_hex("f9606d18e7655ea646fe87393c9b225b76158169c1589010410c9a89f2b5fac1a2");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("17053545763d547573b06c8c3a7304995a31022ae55646d5dbbb5ff9787f08d22fd",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2d9d8aa937088fc468e1f6ca266eca079589759b0e9ec7a38d4aa3c342450ff3d28");
	b = apint_create_from_hex("10cb791ff8735ae3d4c94142ea98145e7f6303b42a46f93d55e841a66e2e63652c2");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("3e6903c92f7beaa83dab380d1106de6614ec794f38e5c0e0e332e569b0737358fea",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("29833ab338dd50493c4c9caa1d8eff5bed05b2d49e804fc31a9677d33392e62fec4");
	b = apint_create_from_hex("20811c33c810d32c584a0f0414b67b505f142e60d48624510186a9ddab8f26d5568");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("4a0456e700ee23759496abae32457aac4c19e135730674141c1d21b0df220d0542c",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Diff signs

	a = apint_create_from_hex("246f744e7b73f3dbb02c419b9ae3e9c4c064385c187dfcf8b55100ccc8c572de4f8");
	b = apint_create_from_hex("-245b1f0abbe3d798c45c373a8128625636c39d729069301d167a7c53ad01d147f63");
	// printf("%s", apint_format_as_hex(a));
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("145543bf901c42ebd00a6119bb876e89a09ae98814ccdb9ed684791bc3a196595",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("4248b0c52f90f534f588a8b9b92073871556d3a845e3ffac51699e99e0c811af9f");
	b = apint_create_from_hex("-74e8f4e2fc96b6d62a3e90c3417d9f51c8a874b40425497bd4d6deb1263fd2e684");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-32a0441dcd05c1a134b5e809885d2bcab351a10bbe4149cf836d40174577c136e5",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2aab80bd6b245dd69f3428702861d359c8eae996c277ce3e902c840d205f7698b2");
	b = apint_create_from_hex("-3eb7b5224ba50698da07cfce316e10fbcdac5b5205a43d429ffc1aabf178d4892f");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-140c3464e080a8c23ad3a75e090c3da204c171bb432c6f040fcf969ed1195df07d",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("34d990d0699d4b37576de24253b80e9f3c98e5c244c50efdf9ebb9e830468e280be");
	b = apint_create_from_hex("-90ffd8c846386d276c5242a1e54d7cab8bb864862afc80e2027e0094d291c5ed66");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2bc99343e539c464e0a8be18356336d483dd5f79e21546efd9c3d9dee31d71c9358",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2c72f309155b5ce539e8ee696aaab057b60e0d3ba305e530f7c1e5f7196d161f366");
	b = apint_create_from_hex("-10e30cbb30c4f5304d5f697f88e03c8282f0860c3156f2be03d5b33ff3d8d40a804");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1b8fe64de49667b4ec8984e9e1ca73d5331d872f71aef272f3ec32b725944214b62",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1b4e0b9b15b38386a0ad084ff34855f69184fe8ecf89dd0a7c091beb2cb57f73a8a");
	b = apint_create_from_hex("-198811e2415b05f2483d966e9d6fe410a486a9dbe3273bdf3dbff54ea774590b99e");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1c5f9b8d4587d94586f71e155d871e5ecfe54b2ec62a12b3e49269c854126680ec",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1725df267e13156913358fa113e25b6aebf1075a8cd6be922e5a834a276279a3fff");
	b = apint_create_from_hex("-2a0aeefb4c230fbbc820e1b94bd9e1615d5f772bab28b4fe9b5d71b1ea9963e3999");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-12e50fd4ce0ffa52b4eb521837f785f6716e6fd11e51f66c6d02ee67c336ea3f99a",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("e6b61abfc0cb5df4c2dda9923803dc6447deb65bd49c679928be9b21051fd87af7");
	b = apint_create_from_hex("-14fd68422b2318ff17d9aeece4cf200137c938eb0d3330151112c0206eda29f5337");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-69206962f16631fcbabd453c14ee23af34b4d854fe9699b7e86d66e5e882c6d840",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("16dac4759fc81af46fb43e79a6059cf24e9500da74a459994f11d2960afbfe7c834");
	b = apint_create_from_hex("-1f5d9e34f4e62d613b4c3575ddaf41eb09436c8e9e70c7a45b36c221c2227b88951");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-882d9bf551e126ccb97f6fc37a9a4f8baae6bb429cc6e0b0c24ef8bb7267d0c11d",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("10177b44e02bfe72d391beba036d68921369006d1629e24266f5e50e5889c0f384f");
	b = apint_create_from_hex("-23a504e50894164566b9280457466c77bd677daee34f17238a2dc4e3dedc3160fdf");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-138d89a0286817d29327694a53d903e5a9fe7d41cd2534e12337dfd58652706d790",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Addition

	a = apint_create_from_hex("2b757ba04aac59feb2bfb9b566ef55c0a8131da4906ff2aa6bd5c4693d0b3ff9605");
	b = apint_create_from_hex("1623bde14871f5949cd437562313f84f4bec9a2b804fc8fee46bf9e109272ed65f3");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("41993981931e4f934f93f10b8a034e0ff3ffb7d010bfbba95041be4a46326ecfbf8",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2a74ff5f19a364e3ad63a0c19fa240cc0d3f5cc18838e9dc4cfaaec64ec07af1ac7");
	b = apint_create_from_hex("fa96e7f149b25259fd5c6754229bf97eac3c834a17ea039791756c8a79c6c4b20");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2b6f96470aed17360760fd28f3c4dcc58beb9944d250d3dfe48c2432d93a41b65e7",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("34eb5b8f977b4e2a24bd6fda99fa71364644b6582405d308a8f714766a366ddbeb5");
	b = apint_create_from_hex("1d6026bc6a89774ce50b82af67a954f7eaeb56e02f9cdebe01046fa748735af7257");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("524b824c0204c57709c8f28a01a3c62e31300d3853a2b1c6a9fb841db2a9c8d310c",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("b28fb6695b85a78b83eb22940d14f2e739be180691c9252250d509d80eecd07128");
	b = apint_create_from_hex("1ea27619b8f73f25ad27ab85aaa310b9333d971771f7b236de77924def83d29e376");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("29cb71804eaf999e65665daeeb745fe7a6d97897db1444890384e2eb70729fa549e",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("6714a3e8cd653c8ccc474c3cd67f3de7a378310b662e06de44631917c36fa029e5");
	b = apint_create_from_hex("26f7a6d91734091a69c3eac4e0bd950f312c770b87ca3dadfc285cc418d139af010");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2d68f117a40a5ce336885f88ae2588edab63fa1c3e2d1e1be06e8e55950833b19f5",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("134fdf7aec2d63285abdbdb7586e72f46059cb82479a08a87d1f429543990330cf4");
	b = apint_create_from_hex("1c60d3e1fe7eeede1858f2f907f88df6e1ced4ff308ba14ea3ed29691cb2e1053bb");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2fb0b35ceaac52067316b0b0606700eb4228a0817825a9f7210c6bfe604be4360af",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("33d5fedd170aa06eb7e3d8be53fff5d4f9c54cdc0ffe76b1d3c926862571ca0507f");
	b = apint_create_from_hex("3232d3ca152df73fe56a967a7bb428484f6f89a37dd2cea39139143f74cb0fecc1d");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("6608d2a72c3897ae9d4e6f38cfb41e1d4934d67f8dd1455565023ac59a3cd9f1c9c",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("17ec2be7d1cee5dab0df498d6b64eacf7c5b0253b459f3576829647fe231f0b0f9e");
	b = apint_create_from_hex("128f5d64ca2fccf7f842452e0d75539cb7ed9939029d9e0f1031365f43761272ee0");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2a7b894c9bfeb2d2a9218ebb78da3e6c34489b8cb6f79166785a9adf25a80323e7e",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1034bc1b33a33fd99ad7fc163c0a3ce954536c1ab0d218030b35a1f5a46d262ba75");
	b = apint_create_from_hex("1662aa7ae1ac68e2f6e6720f1a44f7fc7b9342393ac45c0b2af10c374ef7c3133f8");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("26976696154fa8bc91be6e25564f34e5cfe6ae53eb96740e3626ae2cf364e93ee6d",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2910eaa5f2e9bf61f882dce6f6015ddc39fbc5068138cc423348ab889eb89a7e1d3");
	b = apint_create_from_hex("2a6256c8e9b167efd57c6e6d182f0b2d2a925e5b65b142286018264f81e5d30a288");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("5373416edc9b2751cdff4b540e306909648e2361e6ea0e6a9360d1d8209e6d8845b",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Diff signs

	a = apint_create_from_hex("41db4a51e365ea91046416d119eff4ce75116e62302bfa4f9d115a231ae55a0fef");
	b = apint_create_from_hex("-9a61430862b7f5fc8071755e8a70071440c60ddc06f5dc8eb6fd91d4b7ff7710bf");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-5885f8b67f520b6b7c0d5e8d70801245cbb49f79d6c9e23f19ec37b19d1a1d00d0",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("b0b128a11d3ebd114241aad03d75e7548f5c701515c0e5c22afc2181f3d72e3bf6");
	b = apint_create_from_hex("-275a28fb1ec30794cc7f30b4ca0064732638d68d719fc61de38997850b4fdf8f63c");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-1c4f16710cef1bc3b85b1607c62905fddd430f8c2043b7c1c0d9d56cec126caba46",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("b4a80983a7e13f22bb32d3ca759e7323a0da35e0fce90ebd2caa7d780cecc12a6a");
	b = apint_create_from_hex("-19b2c2ffd17fd765f72fc412a3b4d2e3175b44fb5ee4f7df1142e8bfadf1a8aaf3a");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-e6842679701c373cb7c96d5fc5aebb0dd4da19d4f1666f33e7840e82d22dc984d0",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("25b67b313de9a662b1794edfd7008e6e4a46de2a872a361c5ad9c38385caa1546ba");
	b = apint_create_from_hex("-34a1feb3dc4191a61ca3745024e3b7838e8cd2ed6f34bf42349ee2a2f08e27dab5f");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-eeb83829e57eb436b2a25704de329154445f4c2e80a8925d9c51f1f6ac386864a5",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("db83e2cd33ca43a64d07309f47f6d498659ed0ce06bde25a94d95b3ce9c2c99fdf");
	b = apint_create_from_hex("-7df712bfb7df1ad6005198fb93aa72d115e4a554d9569f903568d7fb0f759aaa3f");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("5d8cd00d7beb28d04cb597a3b44c61c74fba2b792d6742ca5f708341da4d2ef5a0",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1985bcef05f2e20139c8e0d43e822f7659ae988005889b8921d38a84077286eda6b");
	b = apint_create_from_hex("-2c7c98cf2580ecb2a145122ab9d0d4cc1e1fa1cbc997a3e850f9686fb4ac1cd83e0");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-12f6dbe01f8e0ab1677c31567b4ea555c471094bc40f085f2f25ddebad3995ea975",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("2b212a71d8a1b725d045bd01093fe232148d173041786a4f31a3e2e6c818837a074");
	b = apint_create_from_hex("-e8d994a87d02858a94f0e3986fe8172c55b98f2fb3496d44a2ada6d74bfdf8e75");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2a3850dd3024b4a045b0cc1d70cffa1ae8375da111c520e1ed01353ff0cc85811ff",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1dbf5609dc75c010f1acbefac5f0815332f42ebef00b863510457b6de3e5ab5aa27");
	b = apint_create_from_hex("-23866538b145c1c852d9dedf2e916d47faf0361d712f8316cad3a3dfe5e528a6a41");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-5c70f2ed4d001b7612d1fe468a0ebf4c7fc075e8123fce1ba8e287201ff7d4c01a",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1fee8763d6af8ab5e5a6a537832d77549f8b6f5bd1794ca346079623f7e8afb0d8f");
	b = apint_create_from_hex("-189772eb157989d7779ef9a7211e8361b3ba88da5af4e5da4dce799afb151e8ad31");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("7571478c13600de6e07ab90620ef3f2ebd0e681768466c8f8391c88fcd3912605e",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("1ddbb5950609fd02725fa7424d5044b67c5ca3018f94865e27ed83fb20fc0ea285a");
	b = apint_create_from_hex("-2c09609d715ecbc277ceb33872b61c17c29504051813dc1b31b00272a8a6ef4012");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1b1b1f8b2ef410464ae2bc0ec624e2f5003352c13e13489c74d283d3f6719fae848",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Neg Addition

	a = apint_create_from_hex("-336b140034b13002f239ca42708968f6c09c74f0e08a4c6efd762269e1069ee6a02");
	b = apint_create_from_hex("-17c061d7b2200c82196aa3099236d874913a1671f43e043f1b8c1205fa8282c535b");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-4b2b75d7e6d13c850ba46d4c02c0416b51d68b62d4c850ae1902346fdb8921abd5d",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-29b3ba6dbe5783cee3f570acf0198f3a78602586c7f386bcd67072df02677346676");
	b = apint_create_from_hex("-1e6bb04925aec150ce477c96afa5ca587b3092b9295722f88f6f36a134af6bffdac");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-481f6ab6e406451fb23ced439fbf5992f390b83ff14aa9b565dfa9803716df46422",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-267d80d6d925baf1aee586a061f7332c9abc15278b5b77e98343c66e0ee997c4f89");
	b = apint_create_from_hex("-2c6caaf13571e294020cbe91f2f5fb9beabf47838f3c6b92fc5662c17f86a45d877");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-52ea2bc80e979d85b0f2453254ed2ec8857b5cab1a97e37c7f9a292f8e703c22800",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-32943711ef73a87268b176ecedd650f8457d75ba1383061b4c5e2263abfe5f18e5c");
	b = apint_create_from_hex("-2eb470d724d74e5bd599eee0e010cde9a0a0651bbf47a98bf2aa1a1e819f568744d");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-6148a7e9144af6ce3e4b65cdcde71ee1e61ddad5d2caafa73f083c822d9db5a02a9",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-12946329d2dce7f560bb86979af98a8b765b2599e75c082dcc3d6782c522aeb696d");
	b = apint_create_from_hex("-24a95d0b559a5b51e72bbe9207012ab3dab3fb854696858dad7c58dc3284d3effcc");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-373dc0352877434747e74529a1fab53f510f211f2df28dbb79b9c05ef7a782a6939",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-f60c329d284ab3c27401fa04cfb9c41b5810126eb5af29a0fe5e3e052cbe7e6aee");
	b = apint_create_from_hex("-32d28d0a170520f0fc8916526dcd50d41e3cc53b325f026abaeb6ddf183a206c9aa");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-42335033e989cc2d23c935f2bac8ed15d3bdc6621db9f504cad151bf6b060853498",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-3e133b4ca8ca28273a819dde8b9ee22a97cd75748e2fcfdf362a8ac96cd1fee8cc");
	b = apint_create_from_hex("-20615a1de97a8a9790f39006af99d610f6aeca190cc30ae9a880792d9e5cd9f298c");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-24428dd2b4072d1a049ba9e49853c433a02ba17055a607e79be321da3529f9e1258",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-15131be351263306cfe8fb0ee852967130acf2bfc03896aef2e63e8fe7ba593c14a");
	b = apint_create_from_hex("-22066719b94c6887aae6db2f99b1bd9f4cb6e55f426515d0ea2bec2ab709c131280");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-371982fd0a729b8e7acfd63e820454107d63d81f029dac7fdd122aba9ec41a6d3ca",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-d52b42fff29894e47c1fc1b949b519c336d0fb5674361ab27765be9c239589a422");
	b = apint_create_from_hex("-f90f5a3f76efda9d276408a3cb66ca060db91425ae6e09988d8819f351bb199bdb");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-1ce3a9d3f69886f81a383ca5d151be3c9448a0f7c22a4244b04edd88f7550a33ffd",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-1a9b3f47b03c6afbfada97ee51824d0fe305bfadc8f3778176426e3081129cb2b7e");
	b = apint_create_from_hex("-2cb51ef4a2f4afe82cfe3ac45a41e6a4b7d6ba89825d835eaed7313ed1026cabfb2");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-47505e3c53311ae427d8d2b2abc433b49adc7a374b50fae025199f6f5215095eb30",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	// Diff signs

	a = apint_create_from_hex("-27a17d739e11f8290f45f8ec81618bac4c07241fa19d987193873b9fd07d561b657");
	b = apint_create_from_hex("2f461f8d7ea1668e3611c3fef423a517eca217512cdb23abbcbf3ac26ea13b7cb9c");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("7a4a219e08f6e6526cbcb1272c2196ba09af3318b3d8b3a2937ff229e23e561545",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-1663317581d1192c85292dd2fbd78c2d5265cb73d7a132e0d9e0094b5ac50186317");
	b = apint_create_from_hex("2afab5766583006da16b875a6345c2efa0af6472c954a463069e95587db61a8357d");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("14978400e3b1e7411c425987676e36c24e4998fef1b371822cbe8c0d22f118fd266",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-1900353d1cdde2b42d53bfcfcad006283e0b994c3e6477ae8a3e844b5ae9f64e9ed");
	b = apint_create_from_hex("287f477cab546860a356999ef5ef5c1aed6ed6d6fd334f1b22a7f4e26e2bc9df285");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("f7f123f8e7685ac7602d9cf2b1f55f2af633d8abeced76c986970971341d390898",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-1c40f226511a5abd69489c8acdd89d32204a7f09348732aeac181362b5a3a44b7a");
	b = apint_create_from_hex("27c4ff90030be117fe15721e8c67adaeb28f3392293adbe6bd8a41219f81caff80a");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("2600f06d9dfa3b6c2780e855df8a23db908a8ba195f268bbd2c8bfeb742790bac90",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-18760a5ae30130c03d12039f7d9fc5dd1abc2fd6ee4e9a0c7d7b010bf00a494700d");
	b = apint_create_from_hex("5e10a53d0368fe1116362b74582f4d92728d0a42058dea60131065609d783fc1e1");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-1295000712caa0df2baea0e8381cd103f3935f32cdf5bb667c49fab5e632c54ae2c",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-34afdf3b9f6dade4bc320e0d6b9a7296c1794962b6d2cecf9bbad3e230c7f837551");
	b = apint_create_from_hex("1ab769f1f4b066258d012c2a39f7e6e1dca4c351c945bc190d3202a59018377e4ad");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-19f87549aabd47bf2f30e1e331a28bb4e4d48610ed8d12b68e88d13ca0afc0b90a4",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-2dae4ad43dc278fc408aa33c3973334409758bc2a98584140b3314ef6205505b3cc");
	b = apint_create_from_hex("96c849392384e3e6d58d9a7917165afea7fe799d087203f5476be6f7d8718ced26");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-2441c640ab8a2abdd331c994a801cd941ef5a428d8fe63d4b6bc567fe47e378c6a6",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-1c59a5d15f044c13adfca5ad84ad17de31ca0ab560ed6013514f4c44f8bf0beed1d");
	b = apint_create_from_hex("2e5f0a0075c6be73b5553c63542130c794d139753d8fa83b78d3c78c3a7db8155a8");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("1205642f16c27260075896b5cf7418e963072ebfdca2482827847b4741beac2688b",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-18c260ce0106b62467a78d7b3008611c93bb90b79e12cbef6630cc8c4db61cda3ed");
	b = apint_create_from_hex("26321fd426cc5248467bea3f33c8fe1b6e343c9fc9befb01e429426760693557c81");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("d6fbf0625c59c23ded45cc403c09cfeda78abe82bac2f127df875db12b3187d894",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);

	a = apint_create_from_hex("-3087dd44903912be6b6f2898890a8e9862c250d585bb73b1c4b0f06cc793dee34a3");
	b = apint_create_from_hex("2c094850187a92416cb1f3edddf0b59368d0ce822152ac7461cb2e17215e0d67fb8");
	sum = apint_add(a, b);
	ASSERT(0 == strcmp("-47e94f477be807cfebd34aaab19d904f9f182536468c73d62e5c255a635d17b4eb",
					   (s = apint_format_as_hex(sum))));
	apint_destroy(sum);
	apint_destroy(b);
	apint_destroy(a);
	free(s);
}